Controllers/Admin/BookLendsAdminController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using LibraryWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using LibraryWebApp.ViewModels;
using System;
using System.Globalization;

namespace LibraryWebApp.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    [Route("Admin/BookLend")]
    public class BookLendsAdminController : Controller
    {
        private LibraryContext _libraryContext;

        public BookLendsAdminController(LibraryContext context)
        {
            _libraryContext = context;    
        }

        // GET: BookLends
        [HttpGet()]
        [HttpGet("Index")]
        [HttpGet("All")]
        public async Task<IActionResult> Index()
        {
            var books = _libraryContext.BookLend.Include(b => b.IdBookNavigation).Include(b => b.IdUserNavigation);
            return View(await books.OrderBy(b => b.DateLend.Value).ToListAsync());
        }
        // GET: BookLends filtered by book
        [HttpGet("FilteredBook/{id}")]
        public async Task<IActionResult> FilteredBook(int? id)
        {
            if (id == null)
                return BadRequest();
            var booksFiltered = _libraryContext.BookLend.Where(b=>b.IdBook==id).Include(b => b.IdBookNavigation).Include(b => b.IdUserNavigation);
            return View("Index", await booksFiltered.ToListAsync());
        }
        // GET: BookLends filtered by user
        [HttpGet("FilteredUser/{id}")]
        public async Task<IActionResult> FilteredUser(string id)
        {
            if (id == null)
                return BadRequest();
            var booksFiltered = _libraryContext.BookLend.Where(b => b.IdUser == id).Include(b => b.IdBookNavigation).Include(b => b.IdUserNavigation);
            return View("Index", await booksFiltered.ToListAsync());
        }

        // GET: BookLends/Create
        [HttpGet("Create")]
        public IActionResult Create()
        {
            var booksSelect = GetBooksSelectList(false);
            ViewData["BookId"] = booksSelect;
            ViewData["UserId"] = GetUsersSelectList();
            if(booksSelect.Any())
                ViewData["BooksCount"] = GetBooksCountSelectList(booksSelect.FirstOrDefault().Value, "", null, 0);
            return View();
        }

        // POST: BookLends/Create
        [HttpPost("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookLendViewModel bookLendViewModel)
        {
            if (ModelState.IsValid)
            {
                var bookLend = new BookLend
                {
                    DateLend = null, 
                    DateReturn = null,
                    IdBook = bookLendViewModel.IdBook,
                    IdUser = bookLendViewModel.IdUser,
                    Count = bookLendViewModel.Count
                };
                DateTime dateLend, dateReturn; 
                if (DateTime.TryParseExact(bookLendViewModel.DateLend, "dd.MM.yyyy HH:mm", null, DateTimeStyles.None, out dateLend))
                {
                    bookLend.DateLend = dateLend;
                }
                if (DateTime.TryParseExact(bookLendViewModel.DateReturn, "dd.MM.yyyy HH:mm", null, DateTimeStyles.None, out dateReturn))
                {
                    bookLend.DateReturn = dateReturn;
                }
                _libraryContext.BookLend.Add(bookLend);
                await _libraryContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            var booksSelect = GetBooksSelectList(false, bookLendViewModel.IdBook.ToString());
            ViewData["BookId"] = booksSelect;
            ViewData["UserId"] = GetUsersSelectList(bookLendViewModel.IdUser);
            if (booksSelect.Any())
                ViewData["BooksCount"] = GetBooksCountSelectList(bookLendViewModel.IdBook.ToString(), bookLendViewModel.Count.ToString(), null, 0);
            return View(bookLendViewModel);
        }

        // GET: BookLends/Edit/5
        [HttpGet("Edit/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            BookLend bookLend = await _libraryContext.BookLend.SingleOrDefaultAsync(m => m.Id == id);
            if (bookLend == null)
            {
                return NotFound();
            }
            var bookLendViewModel = new BookLendViewModel
            {
                Id = bookLend.Id,
                DateLend = bookLend.DateLend.HasValue ? bookLend.DateLend.Value.ToString("dd.MM.yyyy HH:mm") : "",
                DateReturn = bookLend.DateReturn.HasValue ? bookLend.DateReturn.Value.ToString("dd.MM.yyyy HH:mm") : "",
                IdBook = bookLend.IdBook,
                IdUser = bookLend.IdUser,
                Count = bookLend.Count
            };
            var booksSelect = GetBooksSelectList(true, bookLendViewModel.IdBook.ToString());
            ViewData["BookId"] = booksSelect;
            ViewData["UserId"] = GetUsersSelectList(bookLendViewModel.IdUser);
            if (booksSelect.Any())
                ViewData["BooksCount"] = GetBooksCountSelectList(bookLendViewModel.IdBook.ToString(), bookLendViewModel.Count.ToString(), bookLendViewModel.IdBook.ToString(), bookLendViewModel.Count);
            return View(bookLendViewModel);
        }

        // POST: BookLends/Edit/5
        [HttpPost("Edit/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditBook(BookLendViewModel bookLendViewModel)
        {
            BookLend bookLend = await _libraryContext.BookLend.SingleOrDefaultAsync(b => b.Id == bookLendViewModel.Id);
            if (bookLend == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                bookLend.IdBook = bookLendViewModel.IdBook;
                bookLend.IdUser = bookLendViewModel.IdUser;
                bookLend.Count = bookLendViewModel.Count;
                DateTime dateLend, dateReturn; 
                if (DateTime.TryParseExact(bookLendViewModel.DateLend, "dd.MM.yyyy HH:mm", null, DateTimeStyles.None, out dateLend))
                {
                    bookLend.DateLend = dateLend;
                }
                if (DateTime.TryParseExact(bookLendViewModel.DateReturn, "dd.MM.yyyy HH:mm", null, DateTimeStyles.None, out dateReturn))
                {
                    bookLend.DateReturn = dateReturn;
                }
                _libraryContext.Update(bookLend);
                await _libraryContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            var booksSelect = GetBooksSelectList(true, bookLendViewModel.IdBook.ToString());
            ViewData["BookId"] = booksSelect;
            ViewData["UserId"] = GetUsersSelectList(bookLendViewModel.IdUser);
            if (booksSelect.Any())
                ViewData["BooksCount"] = GetBooksCountSelectList(bookLendViewModel.IdBook.ToString(), bookLendViewModel.Count.ToString(), bookLendViewModel.IdBook.ToString(), bookLend.Count);
            return View("Edit", bookLendViewModel);
        }

        // GET: BookLends/Delete/5
        [HttpGet("Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            BookLend bookLend = await _libraryContext.BookLend.Include(b=>b.IdUserNavigation).SingleOrDefaultAsync(m => m.Id == id);
            if (bookLend == null)
            {
                return NotFound();
            }

            return View(bookLend);
        }

        // POST: BookLends/Delete/5
        [HttpPost("Delete/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            BookLend bookLend = await _libraryContext.BookLend.SingleOrDefaultAsync(m => m.Id == id);
            _libraryContext.BookLend.Remove(bookLend);
            await _libraryContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        private List<SelectListItem> GetBooksSelectList(bool edit, string selectedValue = null)
        {
            var booksInUse = _libraryContext.BookLend.Where(b=>!b.DateReturn.HasValue).GroupBy(b => b.IdBook).ToList();
            var books = new List<SelectListItem>();
            foreach (var book in _libraryContext.Book)
            {
                var booksCanBeSelected = book.Count;
                var currentBookInUse = booksInUse.FirstOrDefault(b => b.Key == book.Id);
                if (currentBookInUse != null)
                    booksCanBeSelected = book.Count - currentBookInUse.Sum(b=>b.Count);
                if (booksCanBeSelected > 0 || (book.Id.ToString() == selectedValue && edit))
                {
                    books.Add(new SelectListItem
                    {
                        Value = book.Id.ToString(),
                        Text = book.Name,
                        Selected = book.Id.ToString() == selectedValue
                    });
                }
            }
            return books.OrderBy(i=>i.Text).ToList();
        }
        private List<SelectListItem> GetUsersSelectList(string selectedValue = null)
        {
            var list = new List<SelectListItem>();
            foreach (var user in _libraryContext.AspNetUsers)
            {
                list.Add(new SelectListItem
                {
                    Value = user.Id,
                    Text = $"{user.LastName} {user.FirstName} {user.SecondName}",
                    Selected = user.Id==selectedValue
                });
            }
            return list.Where(i=>!string.IsNullOrWhiteSpace(i.Text)).OrderBy(i=>i.Text).ToList();
        }

Views/BookLendsAdmin/Create.cshtml
@using System.Threading.Tasks
@model LibraryWebApp.ViewModels.BookLendViewModel

@{
    Layout = "_LayoutAdmin";
}

<div class="content-box-large">
    <div class="panel-heading">
        <div class="panel-title">Lend a book</div>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" role="form" asp-action="Create" asp-controller="BookLendsAdmin">
            <div class="form-group">
                <label asp-for="DateLend" class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                    <div class="input-group date" id="dateTimePicker1">
                        <input asp-for="DateLend" class="form-control">
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar">
                            </span>
                        </span>
                        <span asp-validation-for="DateLend" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="DateReturn" class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                    <div class="input-group date" id="dateTimePicker2">
                        <input asp-for="DateReturn" class="form-control">
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar">
                            </span>
                        </span>
                        <span asp-validation-for="DateReturn" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="IdBook" class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                    <select asp-for="IdBook" class="form-control" asp-items="@((List<SelectListItem>) (ViewData["BookId"]))"></select>
                    <span asp-validation-for="IdBook" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="IdUser" class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                    <select asp-for="IdUser" class="form-control" asp-items="@((List<SelectListItem>) (ViewData["UserId"]))"></select>
                    <span asp-validation-for="IdUser" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Count" class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                    <select asp-for="Count" class="form-control" asp-items="@((List<SelectListItem>) (ViewData["BooksCount"]))"></select>
                    <span asp-validation-for="Count" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input type="submit" class="btn btn-primary" value="Lend" />
                </div>
            </div>
        </form>
    </div>
</div>
@section scripts{
    <script>
        function updateBooksCount() {
            var selectedBook = $("#IdBook").val();
            $.ajax({
                url: '@Url.Action("GetBooksCountSelectList", "BookLendsAdmin")',
                data: { idBook: selectedBook, selectedValue: ""},
                success: function (result) {
                    $("#Count").empty();
                    $.each(result, function (Value, Text) {
                        $("#Count").append($('<option></option>').val(Text.value).html(Text.text));
                    });
                }
            });
        };

        $(function () {
            var dateNow = new Date();
            $('#dateTimePicker1').datetimepicker({
                format: 'DD.MM.YYYY HH:mm',
                daysOfWeekDisabled: [0, 6],
                useCurrent: false,
                disabledTimeIntervals: [[moment().hour(0), moment().hour(8).minutes(59)], [moment().hour(19).minutes(59), moment().hour(24)]],
                allowInputToggle: true,
                defaultDate:moment(dateNow)
            });

            $('#dateTimePicker2').datetimepicker({
                format: 'DD.MM.YYYY HH:mm',
                daysOfWeekDisabled: [0, 6],
                useCurrent: false,
                disabledTimeIntervals: [[moment().hour(0), moment().hour(8).minutes(59)], [moment().hour(19).minutes(59), moment().hour(24)]],
                allowInputToggle: true
            });
            $("#IdBook").change(function(){
                updateBooksCount();
            });
        });
    </script>
}

Views/BookLendsAdmin/Delete.cshtml
@model LibraryWebApp.Models.BookLend

@{
    Layout = "_LayoutAdmin";
}

<form asp-action="Delete" class="form-horizontal" asp-controller="BookLendsAdmin">
    <div class="form-group">
        <h4 class="col-sm-5 control-label">Are you sure you want to delete lend for "@Model.IdUserNavigation.LastName"?</h4>
        <div class="col-sm-7">
            <input type="submit" value="Yes" class="btn btn-default" />
        </div>
    </div>
</form>

Views/BookLendsAdmin/Edit.cshtml
@using LibraryWebApp.ViewComponents
@model LibraryWebApp.ViewModels.BookLendViewModel

@{
    Layout = "_LayoutAdmin";
}

<div class="content-box-large">
    <div class="panel-heading">
        <div class="panel-title">Edit lend</div>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" role="form" asp-action="Edit" asp-controller="BookLendsAdmin">
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="DateLend" class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                    <div class="input-group date" id="dateTimePicker1">
                        <input asp-for="DateLend" class="form-control">
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar">
                            </span>
                        </span>
                        <span asp-validation-for="DateLend" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="DateReturn" class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                    <div class="input-group date" id="dateTimePicker2">
                        <input asp-for="DateReturn" class="form-control">
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar">
                            </span>
                        </span>
                        <span asp-validation-for="DateReturn" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="IdBook" class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                    <select asp-for="IdBook" class="form-control" asp-items="@((List<SelectListItem>) (ViewData["BookId"]))"></select>
                    <span asp-validation-for="IdBook" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="IdUser" class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                    <select asp-for="IdUser" class="form-control" asp-items="@((List<SelectListItem>) (ViewData["UserId"]))"></select>
                    <span asp-validation-for="IdUser" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Count" class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                    <select asp-for="Count" class="form-control" asp-items="@((List<SelectListItem>) (ViewData["BooksCount"]))"></select>
                    <span asp-validation-for="Count" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input type="submit" class="btn btn-primary" value="Save" />
                </div>
            </div>
    </form>
    </div>
</div>
@section scripts{
    <script>
        function updateBooksCount() {
            var selectedBook = $("#IdBook").val();
            $.ajax({
                url: '@Url.Action("GetBooksCountSelectList", "BookLendsAdmin")',
                data: { idBook: selectedBook, selectedValue: "", currentBook: @Model.IdBook },
                success: function (result) {
                    $("#Count").empty();
                    $.each(result, function (Value, Text) {
                        $("#Count").append($('<option></option>').val(Text.Value).html(Text.Text));
                    });
                }
            });
        };
        $(function() {
            var dateNow = new Date();
            $('#dateTimePicker1').datetimepicker({
                format: 'DD.MM.YYYY HH:mm',
                daysOfWeekDisabled: [0, 6],
                useCurrent: false,
                disabledTimeIntervals: [[moment().hour(0), moment().hour(8).minutes(59)], [moment().hour(19).minutes(59), moment().hour(24)]],
                allowInputToggle: true,
                defaultDate:moment(dateNow)
            });

            $('#dateTimePicker2').datetimepicker({
                format: 'DD.MM.YYYY HH:mm',
                daysOfWeekDisabled: [0, 6],
                useCurrent: false,
                disabledTimeIntervals: [[moment().hour(0), moment().hour(8).minutes(59)], [moment().hour(19).minutes(59), moment().hour(24)]],
                allowInputToggle: true
            });
            $("#IdBook").change(function () {
                updateBooksCount();
            });
        });
    </script>
}

Views/BookLendsAdmin/Index.cshtml
@model IEnumerable<LibraryWebApp.Models.BookLend>

@{
    Layout = "_LayoutAdmin";
}
<div class="content-box-large">
    <div class="panel-heading">
        <div class="panel-title">Book lends</div>
        <div><a asp-action="Create" asp-controller="BookLendsAdmin" class="btn btn-default btn-sm">+</a>
        </div>
    </div>
    <div class="panel-body">
        <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered" id="BookLend">
            <thead>
            <tr>
                <th>Date of lend</th>
                <th>Date of return</th>
                <th>Book</th>
                <th>User</th>
                <th>Count</th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                if (!item.DateReturn.HasValue)
                {
                    <tr class="bookInUse">
                        <td>@item.DateLend</td>
                        <td>Book is in use during @((DateTime.Now - item.DateLend).Value.Days) day(s), @((DateTime.Now - item.DateLend).Value.Hours) hour(s) and @((DateTime.Now - item.DateLend).Value.Minutes) minute(s)</td>
                        <td>@item.IdBookNavigation.Name</td>
                        <td>@item.IdUserNavigation.LastName @item.IdUserNavigation.FirstName @item.IdUserNavigation.SecondName</td>
                        <td>@item.Count</td>
                        <td><a asp-controller="BookLendsAdmin" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-default btn-sm">Edit</a></td>
                        <td><a asp-controller="BookLendsAdmin" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default btn-sm">Delete</a></td>
                    </tr>
                }
                else
                {
                    <tr>
                        <td>@item.DateLend</td>
                        <td>@item.DateReturn</td>
                        <td>@item.IdBookNavigation.Name</td>
                        <td>@item.IdUserNavigation.LastName @item.IdUserNavigation.FirstName @item.IdUserNavigation.SecondName</td>
                        <td>@item.Count</td>
                        <td></td>
                        <td><a asp-controller="BookLendsAdmin" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default btn-sm">Delete</a></td>
                    </tr>
                }
            }
            </tbody>
        </table>
    </div>
</div>
@section scripts{
    <link href="/css/dataTables.bootstrap.css" rel="stylesheet" media="screen">
    <script src="/js/jquery.dataTables.min.js"></script>
    <script src="/js/dataTables.bootstrap.js"></script>
    <script>
        $(function() {
            $("#BookLend").dataTable();
        });
    </script>
}