Models/Book.cs
using System;
using System.Collections.Generic;

namespace LibraryWebApp.Models
{
    public partial class Book
    {
        public Book()
        {
            BookLend = new HashSet<BookLend>();
            WishList = new HashSet<WishList>();
        }

        public int Id { get; set; }
        public string Author { get; set; }
        public int? CategoryId { get; set; }
        public string City { get; set; }
        public int? Count { get; set; }
        public DateTime? DateAdded { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
        public int? PagesCount { get; set; }
        public string Publisher { get; set; }
        public int? Year { get; set; }

        public virtual ICollection<BookLend> BookLend { get; set; }
        public virtual ICollection<WishList> WishList { get; set; }
        public virtual Category Category { get; set; }
    }
}

Controllers/Admin/CategoriesAdminController.cs
using System.Linq;
using System.Threading.Tasks;
using LibraryWebApp.Models;
using LibraryWebApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LibraryWebApp.Controllers.Admin
{
    [Authorize(Roles="Admin")]
    [Route("Admin/Categories")]
    public class CategoriesAdminController : Controller
    {
        private LibraryContext _libraryContext;

        public CategoriesAdminController(LibraryContext context)
        {
            _libraryContext = context;    
        }

        // GET: CategoriesAdmin
        [HttpGet()]
        [HttpGet("Index")]
        [HttpGet("All")]
        public async Task<IActionResult> Index()
        {
            var categories = await _libraryContext.Category.Include(c=>c.Book).ToListAsync();
            return View(categories);
        }

        // GET: CategoriesAdmin/Create
        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: CategoriesAdmin/Create
        [HttpPost("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                if (!_libraryContext.Category.AnyAsync(category =>
                    category.Name == categoryViewModel.Name).Result)
                {
                    _libraryContext.Category.Add(new Category
                    {
                        Name = categoryViewModel.Name
                    });
                    await _libraryContext.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("Name", "Name already exists");
            }
            return View(categoryViewModel);
        }

        // GET: CategoriesAdmin/Edit/5
        [HttpGet("Edit/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Category category = await _libraryContext.Category.SingleOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            var categoryViewModel = new CategoryViewModel
            {
                Id = category.Id,
                Name = category.Name
            };
            return View(categoryViewModel);
        }

        [HttpGet("{id}/Books")]
        public async Task<IActionResult> Books(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }
            Category category = await _libraryContext.Category.SingleOrDefaultAsync((m => m.Id == id));
            if (category == null)
            {
                return NotFound();
            }
            var books = _libraryContext.Book.ToList().Where(book => book.CategoryId == id);
            ViewData["CategoryName"] = category.Name;
            return View("Books", books);
        }

        // POST: CategoriesAdmin/Edit/5
        [HttpPost("Edit/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCategory(CategoryViewModel categoryViewModel)
        {
            Category category = await _libraryContext.Category.SingleOrDefaultAsync(m => m.Id == categoryViewModel.Id);
            if (category == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                if (!_libraryContext.Category.AnyAsync(c =>
                    c.Name == categoryViewModel.Name).Result)
                {
                    category.Name = categoryViewModel.Name;
                    _libraryContext.Update(category);
                    await _libraryContext.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("Name", "Name already exists");
            }
            return View(category);
        }

        // GET: CategoriesAdmin/Delete/5
        [HttpGet("Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Category category = await _libraryContext.Category.SingleOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: CategoriesAdmin/Delete/5
        [HttpPost("Delete/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Category category = await _libraryContext.Category.SingleOrDefaultAsync(m => m.Id == id);
            _libraryContext.Category.Remove(category);
            await _libraryContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Controllers/BooksController.cs
using LibraryWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;

namespace LibraryWebApp.Controllers
{
    public class BooksController : Controller
    {
        private const int _productsOnPage = 5;
        private const int _pagesOnPagination = 5;
        private LibraryContext _libraryContext;
        private ILogger<BooksController> _logger;

        public BooksController(LibraryContext context, ILogger<BooksController> logger)
        {
            _libraryContext = context;
            _logger = logger;
        }

        // GET: Books
        //pages from 1 to 5
        public async Task<IActionResult> All(int? page)
        {
            ViewBag.Title = "Books";
            var books = await _libraryContext.Book.Include(b => b.Category).Include(u => u.WishList).ToListAsync();
            return GetPagination(page, books, "All", null);
        }

        private IActionResult GetPagination(int? page, List<Book> books, string action, string routeCategory)
        {
            if (!books.Any())
            {
                return View("Books", books);
            }
            if (page == null || page.Value <= 0)
                page = 1;
            var pagesCount = Math.Ceiling((decimal) books.Count/_productsOnPage);
            if (page.Value > pagesCount)
                return BadRequest();
            var pager = new Pager
            {
                PreviousPage = page.Value >= 2 ? (page.Value - 1).ToString() : "",
                NextPage = page.Value < pagesCount ? (page.Value + 1).ToString() : "",
                CurrentPage = page.Value.ToString(),
                Action = action,
                RouteCategory = routeCategory
            };
            //current page
            var pagesList = new List<string> {page.Value.ToString()};
            if (page.Value == 1)
            {
                for (var i = page.Value + 1; i <= _pagesOnPagination; i++)
                {
                    if (i > pagesCount)
                        continue;
                    pagesList.Add(i.ToString());
                }
            }
            else if (page.Value == 2)
            {
                pagesList.Add((page.Value - 1).ToString());
                for (var i = page.Value + 1; i <= _pagesOnPagination; i++)
                {
                    if (i > pagesCount)
                        continue;
                    pagesList.Add(i.ToString());
                }
            }
            else if (page.Value == pagesCount)
            {
                for (var i = page.Value - 1; i > 0; i--)
                {
                    if (pagesList.Count == _pagesOnPagination)
                        continue;
                    pagesList.Add(i.ToString());
                }
            }
            else if (page.Value == pagesCount - 1)
            {
                pagesList.Add(pagesCount.ToString());
                for (var i = page.Value - 1; i > 0; i--)
                {
                    if (pagesList.Count == _pagesOnPagination)
                        continue;
                    pagesList.Add(i.ToString());
                }
            }
            else if (page.Value == pagesCount - 2)
            {
                pagesList.Add(pagesCount.ToString());
                pagesList.Add((pagesCount - 1).ToString());
                for (var i = page.Value - 1; i > 0; i--)
                {
                    if (pagesList.Count == _pagesOnPagination)
                        continue;
                    pagesList.Add(i.ToString());
                }
            }
            else
            {
                for (var i = 1; i <= _pagesOnPagination; i++)
                {
                    if (i != page.Value)
                        pagesList.Add(i.ToString());
                }
            }
            pager.Pages = pagesList.OrderBy(item => item).ToList();
            ViewBag.pager = pager;
            return View("Books", books.Skip((page.Value - 1)*_productsOnPage).Take(_productsOnPage));
        }

        public async Task<IActionResult> Top()
        {
            var books =
                await
                    _libraryContext.Book.Include(b => b.Category).Include(b => b.WishList).OrderByDescending(b => b.BookLend.Count).ToListAsync();
            return View(books.Take(10));
        }

        public async Task<IActionResult> New()
        {
            var books =
                await
                    _libraryContext.Book.Include(b => b.WishList).Include(b => b.Category)
                        .OrderByDescending(book => book.DateAdded).Take(10)
                        .ToListAsync();
            return View(books);
        }

        public async Task<IActionResult> Category(int? id, int? page)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var category = _libraryContext.Category.FirstOrDefaultAsync(c => c.Id == id).Result;
            if (category == null)
            {
                return BadRequest();
            }
            var books = await _libraryContext.Book.Include(b => b.WishList).Where(b => b.CategoryId == id).ToListAsync();
            ViewBag.Title = category.Name;
            ViewBag.Category = ViewBag.Title;
            ViewBag.CategoryId = category.Id;
            return GetPagination(page, books, "Category", id.ToString());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Book book = await _libraryContext.Book.Include(b => b.Category).SingleOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }
            var booksLend =
                await _libraryContext.BookLend.Where(b => b.IdBook == id && !b.DateReturn.HasValue).ToListAsync();
            ViewBag.BooksLeft = book.Count - booksLend.Count;
            return View(book);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddToWishListPost(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                var adding = await AddToWishList(id);
                if (adding)
                {
                    return RedirectToAction("WishList", "Account");
                }
            }
            return BadRequest();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddToWishListAjax(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                var adding = await AddToWishList(id);
                if (adding)
                {
                    if (ViewData["book_temp"] != null)
                    {
                        var book = (Book)ViewData["book_temp"];
                        return ViewComponent("Book", new {book = book});
                    }
                }
            }
            return BadRequest();
        }
        [Authorize]
        public async Task<bool> AddToWishList(int id)
        {
            try
            {
                var user = await _libraryContext.AspNetUsers.Include(u => u.WishList)
                    .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                var book = await _libraryContext.Book.Include(b => b.Category).Include(b => b.WishList)
                    .FirstOrDefaultAsync(b => b.Id == id);
                if (user != null && book != null)
                {
                    user.WishList.Add(new WishList
                    {
                        DateAdd = DateTime.Now,
                        IdBook = id
                    });
                    await _libraryContext.SaveChangesAsync();
                    ViewData["book_temp"] = book;
                    return true;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("AddToWishList book #{0} - {1}", id, ex.Message);
            }
            return false;
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> RemoveFromWishListPost(int idBook)
        {
            if (User.Identity.IsAuthenticated)
            {
                var removing = await RemoveFromWishList(idBook);
                if (removing)
                {
                    return RedirectToAction("WishList", "Account");
                }
            }
            return BadRequest();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> RemoveFromWishListAjax(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                var removing = await RemoveFromWishList(id);
                if (removing)
                {
                    if (ViewData["book_temp"] != null)
                    {
                        var book = (Book) ViewData["book_temp"];
                        return ViewComponent("Book", new{ book = book});
                    }
                }
            }
            return BadRequest();
        }

        [Authorize]
        public async Task<bool> RemoveFromWishList(int id)
        {
            try
            {
                var user = await _libraryContext.AspNetUsers.Include(u => u.WishList)
                    .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                var book = await _libraryContext.Book.Include(b => b.Category)
                    .Include(b => b.WishList).FirstOrDefaultAsync(b => b.Id == id);
                if (user != null && book != null)
                {
                    var wishBook = user.WishList.FirstOrDefault(w => w.IdBook == id);
                    user.WishList.Remove(wishBook);

Views/CategoriesAdmin/Books.cshtml
@model IEnumerable<LibraryWebApp.Models.Book>

@{
    Layout = "_LayoutAdmin";
}
<div class="content-box-large">
    <div class="panel-heading">
        <div class="panel-title"><a asp-action="Index" asp-controller="CategoriesAdmin" class="btn btn-default btn-sm"> Back</a> Books in @ViewData["CategoryName"]</div>
    </div>
    <div class="panel-body">
        @if (Model.ToList().Any())
        {
            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Author)</th>
                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                    <th>@Html.DisplayNameFor(model => model.Category)</th>
                    <th>@Html.DisplayNameFor(model => model.Count)</th>
                    <th>@Html.DisplayNameFor(model => model.DateAdded)</th>
                    <th>@Html.DisplayNameFor(model => model.Description)</th>
                    <th>@Html.DisplayNameFor(model => model.Year)</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr class="odd gradeX">
                        <td>@Html.DisplayFor(modelItem => item.Author)</td>
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Category.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Count)</td>
                        <td>@Html.DisplayFor(modelItem => item.DateAdded)</td>
                        <td>@Html.DisplayFor(modelItem => item.Description)</td>
                        <td>@Html.DisplayFor(modelItem => item.Year)</td>
                        <td><a asp-controller="BooksAdmin" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-default btn-sm">Edit</a></td>
                        <td><a asp-controller="BooksAdmin" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default btn-sm">Delete</a></td>
                    </tr>
                }
                </tbody>
            </table>
        }
        else
        {
            <h3>There is no books!</h3>
        }
    </div>
</div>

Views/CategoriesAdmin/Create.cshtml
@model LibraryWebApp.ViewModels.CategoryViewModel

@{
    Layout = "_LayoutAdmin";
}
<div class="content-box-large">
    <div class="panel-heading">
        <div class="panel-title">Add Category</div>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" role="form" asp-action="Create" asp-controller="CategoriesAdmin">
            <div class="form-group">
                <label asp-for="Name" class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                    <input asp-for="Name" class="form-control">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input type="submit" class="btn btn-primary" value="Add" />
                </div>
            </div>
        </form>
    </div>
</div>

Views/CategoriesAdmin/Delete.cshtml
@model LibraryWebApp.Models.Category

@{
    Layout = "_LayoutAdmin";
}

<form asp-action="Delete" class="form-horizontal" asp-controller="CategoriesAdmin">
    <div class="form-group">
        <h4 class="col-sm-5 control-label">Are you sure you want to delete category "@Model.Name"?</h4>
        <div class="col-sm-7">
            <input type="submit" value="Yes" class="btn btn-default" />
        </div>
    </div>
</form>

Views/CategoriesAdmin/Edit.cshtml
@model LibraryWebApp.ViewModels.CategoryViewModel

@{
    Layout = "_LayoutAdmin";
}
<div class="content-box-large">
    <div class="panel-heading">
        <div class="panel-title">Edit Category</div>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" role="form" asp-action="Edit" asp-controller="CategoriesAdmin">
            <div class="form-group">
                <label asp-for="Name" class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                    <input asp-for="Name" class="form-control">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input type="submit" class="btn btn-primary" value="Save" />
                </div>
            </div>
        </form>
    </div>
</div>

Views/CategoriesAdmin/Index.cshtml
@model IEnumerable<LibraryWebApp.Models.Category>

@{
    Layout = "_LayoutAdmin";
}

<div class="content-box-large">
    <div class="panel-heading">
        <div class="panel-title">Categories</div>
        <div><a asp-action="Create" asp-controller="CategoriesAdmin" class="btn btn-default btn-sm">+</a></div>
    </div>
    <div class="panel-body">
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                    <th>Count of books</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="odd gradeX">
                        <td class="center">@Html.DisplayFor(modelItem => item.Name)</td>
                        <td class="center">@item.Book.Count</td>
                        <td class="center"><a asp-controller="CategoriesAdmin" asp-action="Books" asp-route-id="@item.Id" class="btn btn-default btn-sm">Go to Books</a></td>
                        <td class="center"><a asp-controller="CategoriesAdmin" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-default btn-sm">Edit</a></td>
                        <td class="center"><a asp-controller="CategoriesAdmin" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default btn-sm">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>