Controllers/Admin/UsersAdminController.cs
using System.Linq;
using System.Threading.Tasks;
using LibraryWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace LibraryWebApp.Controllers.Admin
{
    [Authorize(Roles="Admin")]
    [Route("Admin/Users")]
    public class UsersAdminController : Controller
    {
        private LibraryContext _libraryContext;
        private string _adminEmail;

        public UsersAdminController(LibraryContext context, IOptions<AppSettings> settings)
        {
            _libraryContext = context;
            _adminEmail = settings.Value.AdminEmail;
        }

        // GET: UsersAdmin
        [HttpGet()]
        [HttpGet("Index")]
        [HttpGet("All")]
        public async Task<IActionResult> Index()
        {
            return View(await _libraryContext.AspNetUsers.Where(user=>user.UserName!= _adminEmail).ToListAsync());
        }

        // GET: UsersAdmin/Create
        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View("Register");
        }

        // GET: UsersAdmin/Delete/5
        [HttpGet("Delete/{id}")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AspNetUsers aspNetUsers = await _libraryContext.AspNetUsers.SingleOrDefaultAsync(m => m.Id == id);
            if (aspNetUsers == null)
            {
                return NotFound();
            }

            return View(aspNetUsers);
        }

        // POST: UsersAdmin/Delete/5
        [HttpPost("Delete/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            AspNetUsers aspNetUsers = await _libraryContext.AspNetUsers.SingleOrDefaultAsync(m => m.Id == id);
            _libraryContext.AspNetUsers.Remove(aspNetUsers);
            await _libraryContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Views/UsersAdmin/Delete.cshtml
@model LibraryWebApp.Models.AspNetUsers

@{
    Layout = "_LayoutAdmin";
}


<form asp-action="Delete" class="form-horizontal" asp-controller="UsersAdmin">
    <div class="form-group">
        <h4 class="col-sm-5 control-label">Are you sure you want to delete user "@Model.Email"?</h4>
        <div class="col-sm-7">
            <input type="submit" value="Yes" class="btn btn-default" />
        </div>
    </div>
</form>

Views/UsersAdmin/Index.cshtml
@model IEnumerable<LibraryWebApp.Models.AspNetUsers>

@{
    Layout = "_LayoutAdmin";
}
<div class="content-box-large">
    <div class="panel-heading">
        <div class="panel-title">Users</div>
        <div><a asp-action="Create" asp-controller="UsersAdmin" class="btn btn-default btn-sm">+</a></div>
    </div>
    <div class="panel-body">
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Login</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Second Name</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
            {
                    <tr class="odd gradeX">
                        <td>@Html.DisplayFor(modelItem => item.UserName)</td>
                        <td>@Html.DisplayFor(modelItem => item.FirstName)</td>
                        <td>@Html.DisplayFor(modelItem => item.LastName)</td>
                        <td>@Html.DisplayFor(modelItem => item.SecondName)</td>
                        <td><a asp-controller="BookLendsAdmin" asp-action="FilteredUser" asp-route-id="@item.Id" class="btn btn-default btn-sm">Go to books</a></td>
                        <td><a asp-controller="UsersAdmin" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default btn-sm">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>